### ISSUE TITLE
写一个 I18n 的 vscode扩展

### ISSUE THREAD

**Issue by axetroy** [axetroy/todo#91]
### 初衷/目标

为了我们更方便的写 i18n

初步定义 i18n 文件的格式，不想繁琐，所以拒绝使用JSON

```yaml
# app.i18n.yaml
language: 
  - en
  - zh
  - hk

keys:
  apple.add:
    - Add
    - 添加
    - 添加
  apple.delete:
    - Delete
    - 删除
    - 刪除
  people.say:
    - Hello, {0}
    - 你好, {0}
    - 你好, {0}
```

主要功能包括:

- [ ] 使用``yaml``定义 i18n 文件
- [ ] vscode 支持校验字段，包括语言
- [ ] 导出各常用语言，如Javascript/Typescript/JSON
- [ ] I18n 的模版支持传入参数

### TODO类型

- [ ] 类库
- [x] 框架
- [ ] 服务
- [ ] 命令行工具

### 预计时间

- [ ] 一天
- [x] 一周
- [ ] 两周
- [ ] 一月
- [ ] 更久

### 相关链接

[https://github.com/axetroy/todo](https://github.com/axetroy/todo)
